name: IDK Bruh
on: push
jobs:
  format-infra-pulumi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'
      - uses: extractions/setup-just@v1
      - run: cd infra-pulumi && poetry install
      - run: just infra-pulumi/format

  lint-infra-pulumi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'
      - uses: extractions/setup-just@v1
      - run: cd infra-pulumi && poetry install
      - run: just infra-pulumi/lint

  format-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'
      - uses: extractions/setup-just@v1
      - run: cd service && poetry install
      - run: just service/format

  lint-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'
      - uses: extractions/setup-just@v1
      - run: cd service && poetry install
      - run: just service/lint
